apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopiur
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: kopiur-s3-secret
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: KOPIUR_AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: KOPIUR_AWS_SECRET_ACCESS_KEY
    - secretKey: KOPIA_PASSWORD
      remoteRef:
        key: KOPIUR_ENCRYPTION_KEY