---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi-controller-proxy
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      proxy:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 101
            runAsGroup: 101
            fsGroup: 101
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          proxy:
            image:
              repository: docker.io/library/nginx
              tag: latest
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 200m
                memory: 256Mi
            ports:
              - name: http
                containerPort: 8080
                protocol: TCP
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
    service:
      proxy:
        controller: proxy
        ports:
          http:
            port: &port 80
            targetPort: 8080
    persistence:
      config:
        type: configMap
        name: unifi-proxy-config
        globalMounts:
          - path: /etc/nginx/conf.d
      tmp:
        type: emptyDir
        globalMounts:
          - path: /var/cache/nginx
          - path: /run
    route:
      proxy:
        hostnames:
          - unifi.mrtb.io
        parentRefs:
          - name: gateway
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: unifi-controller-proxy
                port: *port