---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unifi-proxy-config
data:
  unifi.conf: | 
    server {
      listen 8080;
      server_name _;
      client_max_body_size 50m;
      location / {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_pass https://unifi-controller.workloads.svc.cluster.local;
      }
      location /inform {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host \$host;
        proxy_pass http://unifi-controller.workloads.svc.cluster.local:8080/inform;
        proxy_ssl_verify off;
      }
    }