apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: context7
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: context7-mcp-secret
    creationPolicy: Owner
  data:
    - secretKey: CONTEXT_7_MCP_API_KEY
      remoteRef:
        key: CONTEXT_7_MCP_API_KEY