apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karakeep 
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: karakeep-secret
    creationPolicy: Owner
    template:
      data:
        KARAKEEP_NEXTAUTH_SECRET: "{{ .KARAKEEP_NEXTAUTH_KEY }}"
        KARAKEEP_MEILI_MASTER_KEY: "{{ .KARAKEEP_MEILI_MASTER_KEY }}"
        KARAKEEP_OPENAI_API_KEY: "{{ .KARAKEEP_OPENAI_API_KEY }}"
  dataFrom:
    - find:
        path: KARAKEEP_ 
      rewrite:
        - regexp:
            source: "(.*)"
            target: "$1"