apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: litellm-secret
    creationPolicy: Owner
  data:
    - secretKey: LITELLM_MASTER_KEY
      remoteRef:
        key: LITELLM_MASTER_KEY
    - secretKey: UI_USERNAME
      remoteRef:
        key: LITELLM_UI_USERNAME
    - secretKey: UI_PASSWORD
      remoteRef:
        key: LITELLM_UI_PASSWORD
