---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi-controller
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      unifi:
        replicas: 1
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            fsGroup: 999
            fsGroupChangePolicy: "OnRootMismatch"
        initContainers:
          fspermissions:
            image:
              repository: docker.io/library/busybox
              tag: latest
            command: ['/bin/sh', '-c', 'chown -R 999:999 /unifi']
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              readOnlyRootFilesystem: true
        containers:
          app:
            image:
              repository: ghcr.io/jacobalberty/unifi-docker
              tag: v9.4.19@sha256:ef032346e2ebdcadaadeb27e38be55f97e6b5ed6cea333d5d82ae9b58ae4068b
            env:
              TZ: "Europe/Berlin"
              UNIFI_STDOUT: "true"
              CERT_IS_CHAIN: "true"
            resources:
              requests:
                cpu: 500m
                memory: 1Gi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: false
    service:
      app:
        controller: unifi
        ports:
          ui:
            port: &uiport 443
            targetPort: 8443
          inform:
            port: &informport 8080
            targetPort: 8080
    persistence:
      data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 5Gi
        globalMounts:
          - path: /unifi
    route:
      unifi:
        hostnames:
          - unifi-devices.mrtb.io
        parentRefs:
          - name: gateway
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: unifi-controller
                port: *informport