apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gluetun-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: gluetun-secret
    creationPolicy: Owner
  data:
    - secretKey: VPN_SERVICE_PROVIDER
      remoteRef:
        key: GLUETUN_VPN_PROVIDER
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: GLUETUN_WIREGUARD_PRIVATE_KEY
    #- secretKey: WIREGUARD_ADDRESSES
    #  remoteRef:
    #    key: GLUETUN_WIREGUARD_ADDRESS
    #- secretKey: SERVER_CITIES
    #  remoteRef:
    #    key: GLUETUEN_SERVER_CITIES
    - secretKey: SERVER_COUNTRIES
      remoteRef:
        key: GLUETUN_SERVER_COUNTRIES