apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: memini
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: memini-secret
    creationPolicy: Owner
  data:
    - secretKey: LITELLM_API_KEY
      remoteRef:
        key: LITELLM_MASTER_KEY
    - secretKey: MEMINI_API_KEY
      remoteRef:
        key: MEMINI_API_KEY