apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headroom
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: headroom-secret
    creationPolicy: Owner
  data:
    - secretKey: HEADROOM_API_KEY
      remoteRef:
        key: HEADROOM_API_KEY
    - secretKey: HEADROOM_PROXY_TOKEN
      remoteRef:
        key: HEADROOM_API_KEY
