apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: hetzner-dns01
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: hetzner-dns01-account-key
    solvers:
      - dns01:
          webhook:
            solverName: hetzner
            groupName: acme.hetzner.com
            config:
              tokenSecretKeyRef:
                name: hetzner-webhook-secret
                key: token