apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: n8n-secret
    creationPolicy: Owner
    template:
      data:
        N8N_ENCRYPTION_KEY: "{{ .N8N_ENCRYPTION_KEY }}"      
  dataFrom:
    - find:
        path: N8N_
      rewrite:
        - regexp:
            source: "(.*)"
            target: "$1"