---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - ./llmkube/ks.yaml
  - ./litellm-operator/ks.yaml
  - ./litellm/ks.yaml
  - ./context7-mcp/ks.yaml
  - ./open-webui/ks.yaml
  - ./memini/ks.yaml
  - ./headroom/ks.yaml
patches:
  - target:
      kind: Namespace
    patch: |
      - op: add
        path: /metadata/labels
        value:
          resource.kubernetes.io/admin-access: "true"
components:
  - ../../components/namespace
  - ../../components/kopiur/secret