apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: radarr-secret
    creationPolicy: Owner
  data:
    - secretKey: api_key
      remoteRef:
        key: RADARR_API_KEY