# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmmodel_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: opencode-go-hy3
spec:
  modelName: opencode-go/hy3
  params:
    model: openai/hy3
    apiBase: https://opencode.ai/zen/go/v1
    apiKeyRef:
      name: litellm-secret
      key: OPENCODE_GO_API_KEY
    dropParams: true
  info:
    maxInputTokens: 262144
    maxOutputTokens: 131072
    supportsFunctionCalling: true
    supportsPromptCaching: true
    extra:
      supports_reasoning: true
      supports_vision: false
      input_cost_per_token: 0.00000014
      output_cost_per_token: 0.00000058
      cache_read_input_token_cost: 0.000000035
