# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmmodel_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: opencode-go-minimax-m2-7
spec:
  modelName: opencode-go/minimax-m2.7
  params:
    model: anthropic/minimax-m2.7
    apiBase: https://opencode.ai/zen/go/v1
    apiKeyRef:
      name: litellm-secret
      key: OPENCODE_GO_API_KEY
    dropParams: true
  info:
    maxInputTokens: 204800
    maxOutputTokens: 131072
    supportsFunctionCalling: true
    supportsPromptCaching: true
    extra:
      supports_reasoning: true
      supports_vision: false
      input_cost_per_token: 0.0000003
      output_cost_per_token: 0.0000012
      cache_read_input_token_cost: 0.00000006
      cache_creation_input_token_cost: 0.000000375
