---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmmodel_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: opencode-go-qwen3-6-plus
spec:
  modelName: opencode-go/qwen3.6-plus
  params:
    model: anthropic/qwen3.6-plus
    apiBase: https://opencode.ai/zen/go
    apiKeyRef:
      name: litellm-secret
      key: OPENCODE_GO_API_KEY
    dropParams: true
  info:
    maxInputTokens: 262144
    maxOutputTokens: 32768
    supportsFunctionCalling: true
    supportsPromptCaching: true
    extra:
      supports_reasoning: true
      input_cost_per_token: 0.0000005
      input_cost_per_token_above_272k_tokens: 0.000002    # actually >256K in source table
      output_cost_per_token: 0.000003
      output_cost_per_token_above_272k_tokens: 0.000006    # actually >256K in source table
      cache_creation_input_token_cost: 0.000000625