# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmmodel_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: opencode-go-qwen3-7-plus
spec:
  modelName: opencode-go/qwen3.7-plus
  params:
    model: anthropic/qwen3.7-plus
    apiBase: https://opencode.ai/zen/go/v1
    apiKeyRef:
      name: litellm-secret
      key: OPENCODE_GO_API_KEY
    dropParams: true
  info:
    maxInputTokens: 1000000
    maxOutputTokens: 131072
    supportsFunctionCalling: true
    supportsPromptCaching: true
    extra:
      supports_reasoning: true
      supports_vision: true
      input_cost_per_token: 0.0000004
      output_cost_per_token: 0.0000016
      cache_read_input_token_cost: 0.00000004
      cache_creation_input_token_cost: 0.0000005