# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmmodel_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: opencode-go-deepseek-v4-pro
spec:
  modelName: opencode-go/deepseek-v4-pro
  params:
    model: openai/deepseek-v4-pro
    apiBase: https://opencode.ai/zen/go/v1
    apiKeyRef:
      name: litellm-secret
      key: OPENCODE_GO_API_KEY
    dropParams: true
  info:
    maxInputTokens: 1048576
    maxOutputTokens: 384000
    supportsFunctionCalling: true
    supportsPromptCaching: true
    extra:
      supports_reasoning: true
      supports_vision: false
      input_cost_per_token: 0.00000066
      output_cost_per_token: 0.00000198
      cache_read_input_token_cost: 0.000000022
