apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: searxng
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: searxng-secret
    creationPolicy: Owner
  data:
    - secretKey: SEARXNG_SECRET
      remoteRef:
        key:  SEARXNG_SECRET