---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hetzner-webhook-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: hetzner-webhook-secret
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: CERTMANAGER_HETZNER_API_KEY