---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./hetzner-webhook-helmrepo.yaml
  - ./hetzner-webhook-helmrelease.yaml
  - ./hetzner-webhook-externalsecret.yaml