apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex 
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: dex-secret
    creationPolicy: Owner
    template:
      data:
        config.yaml: "{{ .DEX_CONFIG }}"
  data:
    - secretKey: DEX_CONFIG
      remoteRef:
        key: DEX_CONFIG