---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./httproute.yaml
  - ./helmrepository.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: dex-helm-values
    files:
      - values.yaml=./values.yaml
configurations:
  - kustomizeconfig.yaml