apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: open-webui-secret
    creationPolicy: Owner
  data:
    - secretKey: GITHUB_CLIENT_ID
      remoteRef:
        key: OPEN_WEBUI_GITHUB_CLIENT_ID
    - secretKey: GITHUB_CLIENT_SECRET
      remoteRef:
        key: OPEN_WEBUI_GITHUB_CLIENT_SECRET
    - secretKey: WEBUI_SECRET_KEY
      remoteRef:
        key: OPEN_WEBUI_SECRET_KEY
    - secretKey: MEMINI_API_KEY
      remoteRef:
        key: MEMINI_API_KEY
